vich_uploader:
    db_driver: orm

    mappings:
        objets:
            uri_prefix: /uploads/objets
            upload_destination: '%kernel.project_dir%/public/uploads/objets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
